### ISSUE TITLE
Change 'weather' provider

### ISSUE THREAD

**Issue by ArcasCZ** [pumpkin-py/pumpkin-fun#94]
From what I've seen and heard, the Weather API that is now used is highly inaccurate.

I've been recommended to switch to https://yr.no/ (https://developer.yr.no/doc/).

Good thing is, there's already python package, that supports this API: https://pypi.org/project/python-yr/

**Comment by sinus-x** [comment]
I had a research into alternative providers on my personal backlog. I didn't know Yr had public API, this could save a lot of time.

That PyPI Project seems to be 404ing, so we'll have to be using the API directly. It's just asking for JSON, it won't make much difference.

Implementation requirements:
- Try to copy the current UI as close as possible. This includes the fields and the scrolling aspect of the forecast.
- Follow their [Terms of Service](https://developer.yr.no/doc/TermsOfService/).
  - For identification, link to the source code (either the GitHub organization, or the GitHub Fun repository) and include the bot ID (e.g. the integer given to all user and bot users).
  - Cache the results. LRU cache could be enough.
  - Follow the header requirements. Expires, If-Modified-Since.
  - Ensure the limit of 20 requests per second. We won't probably ever hit that limit, but we should be checking it.
  - Include the link to yr.no in the embed footer.
